### PR TITLE
Renaming is_vertical to vertical since it does not follow JS standards for property names

### LINKED ISSUE #20: The property name is_vertical does not follow JS standards
Snake case properties are not a standard in JS projects. Is there any particular reason to use it this way?

### PR DESCRIPTION
**Pull request by thiagozanetti**
- Bumped dependencies to fix a high severity security issue and to make the project up-to-date;
- Renamed `is_vertical` to `vertical` to follow the standards;
- Fixed some minor lint errors regarding indentation.

fix #20

### CODE REVIEW

**Comment by thiagozanetti** [comment]
Nice job you've done, btw. Just trying to contribute. Feel free to reject if you think it doesn't make any sense or if you have whatever reason to keep it this way. Stay strong! 💪🏿

**Comment by SharifClick** [comment]
Thanks for the pr @thiagozanetti, in many projects is_vertical been already used, we have to think about backward compability.

**Comment by gaweki** [comment]
it's have conflict @thiagozanetti

**Comment by thiagozanetti** [comment]
Yeah, I'll have a look on that some time next week. I have a lot on my plate at the moment. :)

**Comment by gaweki** [comment]
can i help solve the conflict?

**Comment by thiagozanetti** [comment]
@gaweki go ahead, please.

**Comment by gaweki** [comment]
hello @thiagozanetti , i just make a PR.

**Comment by thiagozanetti** [comment]
I'll close this PR to start over with a fresh copy since there are many conflicts here.

**Pull request closed without merging**
